#!/bin/bash
#====================================================
#   SCRIPT:                   FIND IP'S - NMAP
#   DESARROLLADO POR:         JENN VALENTINE 
#   FECHA DE ACTUALIZACIÃ“N:  01-04-2024 
#   CONTACTO POR TELEGRAMA:   https://t.me/JennValentine
#   GITHUB OFICIAL:           https://github.com/JennValentine/Findips
#====================================================

# Paleta de colores
reset="\033[0m"       # Restablecer todos los estilos y colores
bold="\033[1m"        # Texto en negrita
italic="\033[3m"      # Texto en cursiva
underline="\033[4m"   # Texto subrayado
blink="\033[5m"       # Texto parpadeante
reverse="\033[7m"     # Invertir colores de fondo y texto
hidden="\033[8m"      # Texto oculto (generalmente invisible)

# Colores de texto
black="\033[0;30m"     # Negro
red="\033[0;31m"       # Rojo
green="\033[0;32m"     # Verde
yellow="\033[0;33m"    # Amarillo
blue="\033[0;34m"      # Azul
magenta="\033[0;35m"   # Magenta
cyan="\033[0;36m"      # Cian
white="\033[0;37m"     # Blanco

# Colores de fondo
bg_black="\033[0;40m"     # Fondo Negro
bg_red="\033[0;41m"       # Fondo Rojo
bg_green="\033[0;42m"     # Fondo Verde
bg_yellow="\033[0;43m"    # Fondo Amarillo
bg_blue="\033[0;44m"      # Fondo Azul
bg_magenta="\033[0;45m"   # Fondo Magenta
bg_cyan="\033[0;46m"      # Fondo Cian
bg_white="\033[0;47m"     # Fondo Blanco

# Iconos
checkmark="${green}[++]${reset}"
error="${red}[--]${reset}"
info="${yellow}[**]${reset}"
process="${magenta}[>>]${reset}"
indicator="${red}==>${reset}"

# Barra de separación
barra="${blue}|--------------------------------------------|${reset}"
bar="${yellow}--------------------------------------------${reset}"

# Comprobación de permisos de root
[[ "$(whoami)" != "root" ]] && {
    echo -e "\n${yellow}[${red}Error${yellow}] ${white}- ${yellow}Necesitas ejecutar esto como administrador (root)${reset}"
    echo -e "\n${green} sudo $0 ${reset}"
    exit 0
}

Acciones() {
    echo -e "\n${info} ${green}Buscando Ip's Activas en la red ...\n"

    # Obtener la dirección IP y la dirección MAC
    ip=$(ip addr | grep inet | grep -v inet6 | grep -v "host lo" | awk '{print $2}' | awk -F "/" '{print $1}')
    mac=$(ip addr | grep link/ether | awk '{print $2}')

    # Obtener la version arp-scan
    version_nmap=$(nmap --version | grep 'Nmap version' | awk '{print $1, $2, $3}')

    # Mostrar el tipo de escaneo de red, la dirección IP, la dirección MAC, la TTL y Posible Sistema 
    echo -ne "${indicator} ${green}Escaneo de red:     ${white}$version_nmap\n"
    echo -ne "${indicator} ${green}Dirección IP:       ${white}$ip\n"
    echo -ne "${indicator} ${green}Dirección MAC:      ${white}$mac\n"

    # Obtener el rango de red
    interface=$(ip route show default | awk '/default/ {print $5}')
    network=$(ip route | grep $interface | awk '{print $1}')

    # Mostrar el rango de red
    echo -ne "${indicator} ${green}Rango de Red:       ${white}$network\n\n"

    ip=$(ip addr | grep inet | grep -v inet6 | grep -v "host lo" | awk '{print $2}' | awk -F "/" '{print $1}')
    gateway=$(ip route show | awk '(NR == 1) { print $3}')

    # Ejecutar nmap para obtener las IP activas y direcciones MAC
    nmap_output=$(sudo nmap -sn $gateway/24 | grep -E "(Nmap scan report for|MAC Address)" | sed -E 's/(Nmap scan report for |MAC Address: )//g' | awk 'NR%2{printf "%s ",$0;next} 1')

    # Inicializar variable para almacenar la salida formateada
    formatted_output=""

    # Iterar sobre cada línea de la salida de nmap
    while IFS= read -r line; do
        # Extraer la IP y la MAC de la línea
        ip=$(echo "$line" | awk '{print $1}')
        mac=$(echo "$line" | awk '{print $2}')
        fab=$(echo "$line" | sed -E 's/.*\(([^)]+)\).*/\1/')


        # Ejecutar ping para obtener el TTL
        ttl=$(ping -c 1 -n -W 1 "$ip" | grep "ttl=" | awk -F 'ttl=' '{print $2}' | awk '{print $1}')

        # Determinar el sistema operativo
        if [[ $ttl -le 64 && $ttl -ge 1 ]]; then
            os="Linux"
        elif [[ $ttl -ge 65 && $ttl -le 128 ]]; then
            os="Windows"
        elif [[ $ttl -ge 129 && $ttl -le 191 ]]; then
            os="macOS"
        elif [[ $ttl -ge 192 && $ttl -le 254 ]]; then
            os="Cisco IOS"
        else
            os="Unknown"
        fi

        # Agregar la línea formateada a la salida
        formatted_output+="${ttl}\t${os}\t${ip}\t${mac}\t${fab}\n"

    done <<< "$nmap_output"

    # Mostrar la salida formateada
    echo -e "${blue}Ip's Activas:\n"
    echo -e "${cyan}TTL\tOS\tIP Address\tMAC Address\t\tFabricante"
    echo -e "${green}$formatted_output"
    echo -e "${checkmark} ${green} Escaneo finalizado"

    echo -e "\n${yellow}${info} ${white}GITHUB OFICIAL: ${green}https://github.com/JennValentine/Findips\n"
    echo -e "$barra"
}

# Llamar a la función Acciones
Acciones

# Fin del script
