#!/bin/bash
#====================================================
#   SCRIPT:                   FIND IP'S - NMAP
#   DESARROLLADO POR:         JENN VALENTINE 
#   FECHA DE ACTUALIZACIÃ“N:  01-04-2024 
#   CONTACTO POR TELEGRAMA:   https://t.me/JennValentine
#   GITHUB OFICIAL:           https://github.com/JennValentine/Findips
#====================================================

# Paleta de colores
reset="\033[0m"       # Restablecer todos los estilos y colores

# Colores de texto
black="\033[0;30m"     # Negro
red="\033[0;31m"       # Rojo
green="\033[0;32m"     # Verde
yellow="\033[0;33m"    # Amarillo
blue="\033[0;34m"      # Azul
magenta="\033[0;35m"   # Magenta
cyan="\033[0;36m"      # Cian
white="\033[0;37m"     # Blanco

# Iconos
checkmark="${green}[++]${reset}"
error="${red}[--]${reset}"
info="${yellow}[**]${reset}"
process="${magenta}[>>]${reset}"
indicator="${red}==>${reset}"

# Barra de separación
barra="${blue}|--------------------------------------------|${reset}"

# Comprobación de permisos de root
[[ "$(whoami)" != "root" ]] && {
    echo -e "\n${yellow}[${red}Error${yellow}] ${white}- ${yellow}Necesitas ejecutar esto como administrador (root)${reset}"
    echo -e "\n${green} sudo $0 ${reset}"
    exit 0
}

Acciones() {
    echo -e "\n${info} ${green}Buscando Ip's Activas en la red ...\n"

    # Obtener la dirección IP y la dirección MAC
    ip=$(ip addr | grep inet | grep -v inet6 | grep -v "host lo" | awk '{print $2}' | awk -F "/" '{print $1}')
    mac=$(ip addr | grep link/ether | awk '{print $2}')

    # Mostrar el tipo de escaneo de red, la dirección IP y la dirección MAC
    echo -ne "${indicator} ${green}Escaneo de red:     ${white}nmap\n"
    echo -ne "${indicator} ${green}Dirección IP:       ${white}$ip\n"
    echo -ne "${indicator} ${green}Dirección MAC:      ${white}$mac\n"

    # Obtener el rango de red
    interface=$(ip route show default | awk '/default/ {print $5}')
    network=$(ip route | grep $interface | awk '{print $1}')

    # Mostrar el rango de red
    echo -ne "${indicator} ${green}Rango de Red:       ${white}$network\n\n"

    ip=$(ip addr | grep inet | grep -v inet6 | grep -v "host lo" | awk '{print $2}' | awk -F "/" '{print $1}')
    gateway=$(ip route show | awk '(NR == 1) { print $3}')
    ###findip=`sudo nmap -sn $gateway/24 | grep report | awk -F for '{ print $2 }'`
    ###findip=$(sudo nmap -sn $gateway/24 | grep -E "(Nmap scan report for|MAC Address)" | sed -E 's/(Nmap scan report for |MAC Address: )//g' | awk 'NR%2{printf "%s ",$0;next} 1' | awk '{print $1, $2, $3}')
    findip=$(sudo nmap -sn $gateway/24 | grep -E "(Nmap scan report for|MAC Address)" | sed -E 's/(Nmap scan report for |MAC Address: )//g' | awk 'NR%2{printf "%s ",$0;next} 1')
    
    echo -e "${blue}Ip's Activas:\n"
    echo -e "${cyan}IP Address\tMAC Address\t    Fabricante${green}"
    echo -e "$findip" | awk '{printf "%-16s%-20s%s\n", $1, $2, $3}'
    echo -e "\n${checkmark} ${green} Escaneo finalizado\n"

    ###echo -e "${blue}Ip's Activas:\n\n${green}$findip"
    ###echo -e "\n${checkmark} ${green} Escaneo finalizado\n"

    echo -e "\n${yellow}${info} ${white}GITHUB OFICIAL: ${green}https://github.com/JennValentine/Findips\n"
    echo -e "$barra"
}

# Llamar a la función Acciones
Acciones

# Fin del script
