#!/bin/bash

Acciones() {
    echo -e "\n\033[01;33m[**] Buscando Ip's Activas en la red ...\n"

    ip=$(ip addr | grep inet | grep -v inet6 | grep -v "host lo" | awk '{print $2}' | awk -F "/" '{print $1}')
    echo -ne "\033[1;31mDirección IP: \033[1;37m$ip \n\n\033[01;32m"

    ip=$(ip addr | grep inet | grep -v inet6 | grep -v "host lo" | awk '{print $2}' | awk -F "/" '{print $1}')
    gateway=$(ip route show | awk '(NR == 1) { print $3}')
    findip=`nmap -sn $gateway/24 | grep report | awk -F for '{ print $2 }'`

    echo -e "\033[1;32mIp's Activas:\n\n\033[01;37m$findip\n"
    echo -e "\n\033[1;33m[**] Escaneo finalizado\n"
    echo -e "\033[0;34m|--------------------------------------------|"

}
Acciones

