#!/bin/bash

Acciones() {
    echo -e "\n\033[01;33m[**] Buscando Ip's Activas en la red ...\n"

    ip=$(ip addr | grep inet | grep -v inet6 | grep -v "host lo" | awk '{print $2}' | awk -F "/" '{print $1}')
    echo -ne "\033[1;31mDirección IP: \033[1;37m$ip \n\n\033[01;32m"

    interface=$(ip route show default | awk '/default/ {print $5}')
    scan_results=$(arp-scan --localnet --interface=$interface)

    # Eliminar la línea que contiene información de la interfaz
    scan_results=$(echo "$scan_results" | sed "/Interface: $interface/d")

    # Imprimir solo las líneas que contienen una dirección IP
    echo "$scan_results" | grep -E "(([0-9]{1,3}\.){3}[0-9]{1,3})"

    echo -e "\n\033[1;33m[**] Escaneo finalizado\n"
    echo -e "\033[0;34m|--------------------------------------------|"
}
Acciones